image: python2.7
env:
script:
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - sudo apt-get install -y software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible
  - sudo apt-get update sudo
  - sudo apt-get install -y ansible
notify:
  email:
    recipients:
      - dennis@wpengine.com
